=== CikeTheBear/U-Tad_INSD/FUDW/Unidad_1/fundamentos.dtd
<!ELEMENT fundamentos (fundamento, profesora, alumnos)>

<!ELEMENT fundamento (titulo, dia, hora, horas)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT horas (#PCDATA)>

<!ELEMENT profesora (nombre, apellido1, apellido2)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido1 (#PCDATA)>
<!ELEMENT apellido2 (#PCDATA)>

<!ELEMENT alumnos ((alumno | alumna)+)>
<!ELEMENT alumno (nombre, apellido1, apellido2)>
<!ELEMENT alumna (nombre, apellido1, apellido2)>

=== CikeTheBear/U-Tad_INSD/FUDW/Unidad_1/fundamentos.xml
<!DOCTYPE fundamentos SYSTEM "fundamentos.dtd">

<fundamentos>
    <fundamento>
        <titulo>Fundamentos del desarrollo web</titulo>
        <dia>Viernes</dia>
        <hora>19:00</hora>
        <horas>20</horas>
    </fundamento>

    <profesora>
        <nombre>Natalia</nombre>
        <apellido1>Matarranz</apellido1>
        <apellido2>Gonzalez</apellido2>
    </profesora>

    <alumnos>
        <alumno>
            <nombre>Carlos</nombre>
            <apellido1>De Almeida</apellido1>
            <apellido2>Romanelli</apellido2>
        </alumno>
        
        <alumna>
            <nombre>Giovanna</nombre>
            <apellido1>Amador</apellido1>
            <apellido2>Morillo</apellido2>
        </alumna>
    </alumnos>
</fundamentos>
